# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-19 05:35
from __future__ import unicode_literals

import Onway.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Onway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, validators=[Onway.validators.validate_url, Onway.validators.validate_dot_com])),
                ('shortcode', models.CharField(max_length=15, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
